// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.TypedDecorator.CallableInterceptorDescriptor.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.Utils.TypeRquest.#ctor(System.Type,MassiveDynamicProxyGenerator.Utils.TypedDecoratorType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.DynamicProxy.DynamicInvocation.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.TypedDecorator.CallableInvocation.#ctor(System.Action{MassiveDynamicProxyGenerator.ICallableInvocation})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.ProxygGeneratorSettings.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.TypedProxy.TypedProxyInvocation.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.AbstractTypeBuilder`1.#ctor(System.Reflection.Emit.TypeBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.TypedDecorator.CallableInvocationDescriptor.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.Utils.KoreanAlphabet.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.TypedInstanceProxy.InstanceProvicerDescriptor.#ctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.TypedDecorator.GenerateUnion.#ctor(System.Reflection.MethodInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.TypedProxy.InvocationDescriptor.#ctor(System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.Utils.MultyTypeRquest.#ctor(System.Type[],MassiveDynamicProxyGenerator.Utils.TypedDecoratorType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.NullInterceptor.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements must appear in the correct order", Justification = "Uniform coding stype.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.NullAsyncInterceptor.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0008:Use explicit type", Justification = "var used for Type or TypeInfo.", Scope = "member", Target = "~M:MassiveDynamicProxyGenerator.TypedProxy.InvocationDescriptor.#ctor(System.Type)")]